//
//  ArticleListInteractor.swift
//  NewYorkTimesArticles
//
//  Created by shairjeel ahmed on 24/07/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleListBusinessLogic
{
    func getArticlesFromApi(request: ListArticles.fetchArticle.Request)
}

protocol ArticleListDataStore
{
    //var name: String { get set }
}

class ArticleListInteractor: ArticleListBusinessLogic, ArticleListDataStore
{
    var presenter: ArticleListPresentationLogic?
    var worker: ArticleListWorker?
    
    // MARK: Call Api
    
    func getArticlesFromApi(request: ListArticles.fetchArticle.Request)
    {
        let service = NetworkService()
        worker = ArticleListWorker(service: service)
        worker?.fetch(request: request, completion: { [weak self] result in
            switch result{
            case .success(let articles):
                let response = ListArticles.fetchArticle.Response(articles: articles)
                self?.presenter?.presentFetchedArticles(response: response)
            case .failure(let error):
                print(error)
            }
        })
    }
}
