//
//  ArticleListModels.swift
//  NewYorkTimesArticles
//
//  Created by shairjeel ahmed on 24/07/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListArticles
{
    // MARK: Use cases
    
    enum fetchArticle
    {
        struct Request
        {
            var periodSection:String
        }
        struct Response
        {
            var articles: [Article]
        }
        struct ViewModel
        {
            struct DisplayedArticle
            {
                var title: String
                var authorNames: String
                var date: String
                var imageUrl: String?
            }
            var displayedArticles: [DisplayedArticle]
        }
    }
}


struct ArticleData:Decodable{
    var results:[Article]?
}

struct Media:Decodable{
    var mediaMetadata:[MediaMetaData]?
    
    enum CodingKeys:String,CodingKey {
           case mediaMetadata = "media-metadata"
       }
}

struct MediaMetaData:Decodable{
    var url:String?
}


struct Article:Decodable{
    var title: String
    var published_date: String
    var byline: String
    var media:[Media]?
}
